name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make
    
    - name: Build project
      run: make all
    
    - name: Run tests
      run: make test
    
    - name: Check if binary runs
      run: |
        timeout 5s ./binary_clock || [ $? -eq 124 ]
        echo "Binary clock runs successfully!"
    
    - name: Clean build artifacts
      run: make clean