name: CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'tests/**'
      - 'Makefile'
      - '.github/workflows/**'
      - 'CLAUDE.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'tests/**'
      - 'Makefile'
      - '.github/workflows/**'
      - 'CLAUDE.md'

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
            
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make
    
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Xcode command line tools should already be available
        which gcc || which clang
        which make
    
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          make
    
    - name: Clean any existing build artifacts (Unix)
      if: matrix.os != 'windows-latest'
      run: make clean || true
      shell: bash
    
    - name: Clean any existing build artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: make clean || true
      shell: msys2 {0}
    
    - name: Build project (Unix)
      if: matrix.os != 'windows-latest'
      run: make all
      shell: bash
    
    - name: Build project (Windows)
      if: matrix.os == 'windows-latest'
      run: make all
      shell: msys2 {0}
    
    - name: Run tests (Unix)
      if: matrix.os != 'windows-latest'
      run: make test
      shell: bash
    
    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      run: make test
      shell: msys2 {0}
    
    - name: Test CLI functionality (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "Testing help functionality..."
        ./binary_clock --help
        echo "Testing default single output (emoji)..."
        ./binary_clock
        echo "Testing binary display mode..."
        ./binary_clock --display=binary
        echo "Testing JSON display mode..."
        ./binary_clock --display=json
        echo "Testing raw API display mode..."
        ./binary_clock --display=raw
        echo "Testing loop mode briefly..."
        timeout 3s ./binary_clock --loop || [ $? -eq 124 ] || [ $? -eq 142 ]
        echo "All CLI tests passed successfully!"
    
    - name: Test CLI functionality (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        echo "Testing help functionality..."
        ./binary_clock --help
        echo "Testing default single output (emoji)..."
        ./binary_clock
        echo "Testing binary display mode..."
        ./binary_clock --display=binary
        echo "Testing JSON display mode..."
        ./binary_clock --display=json
        echo "Testing raw API display mode..."
        ./binary_clock --display=raw
        echo "Testing loop mode briefly..."
        ./binary_clock --loop &
        CLOCK_PID=$!
        sleep 3
        kill $CLOCK_PID 2>/dev/null || true
        wait $CLOCK_PID 2>/dev/null || true
        echo "All CLI tests passed successfully!"
    
    - name: Test CLI functionality (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "Testing help functionality..."
        ./binary_clock.exe --help
        echo "Testing default single output (emoji)..."
        ./binary_clock.exe
        echo "Testing binary display mode..."
        ./binary_clock.exe --display=binary
        echo "Testing JSON display mode..."
        ./binary_clock.exe --display=json
        echo "Testing raw API display mode..."
        ./binary_clock.exe --display=raw
        echo "Testing loop mode briefly..."
        ./binary_clock.exe --loop &
        CLOCK_PID=$!
        sleep 3
        kill $CLOCK_PID 2>/dev/null || true
        wait $CLOCK_PID 2>/dev/null || true
        echo "All CLI tests passed successfully!"
      shell: msys2 {0}
    
    - name: Clean build artifacts (Unix)
      if: matrix.os != 'windows-latest'
      run: make clean
      shell: bash
    
    - name: Clean build artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: make clean
      shell: msys2 {0}